site_name: COGS Docs
site_url: http://cogs.club/rucogs-docs
site_description: Documentation of the COGS infrastructure
repo_url: https://github.com/rucogs/rucogs-infrastructure
repo_name: rucogs/rucogs-infrastructure
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://cogs.club/discord
  extra_css: [extra.css]
plugins:
  - social:
      cards_layout_options:
        background_color: "#b3002d"
        font_family: Urbanist
  - search:
      lang: en
theme:
  name: material
  logo: assets/cogs-logo-white.svg
  favicon: images/cogs-logo.ico
  font:
    text: Roboto
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css
