site_name: RUCOGS Docs 📕
site_url: http://cogs.club/rucogs-docs
repo_url: https://github.com/rucogs/rucogs-infrastructure
repo_name: rucogs/rucogs-infrastructure
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://cogs.club/discord
theme:
  name: material
  logo: assets/cogs-logo-white.svg
  favicon: images/cogs-logo.ico
  font:
    text: Urbanist Mono
  palette:
    - primary: custom

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css
