name: build-sphinx-to-gh-pages

env:
  GITHUB_REPOSITORY: rucogs/rucogs-docs
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: 
  push:
    branches: [ main ]


jobs:

  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - name: Get prerequisites and clone repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x "docs/buildsite.sh"
          "docs/buildsite.sh"
        shell: bash